### ISSUE TITLE
Being able to use Mumuki without Github User

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/mumuki-platform#101]
As the initial contact with the tool is the one that matters for gathering users, this feature is crucial. Nevertheless, I can live without it.

It'd be great to save the progress state for the current session and remember it and associate it to the user if he/she decides to login to github.

**Comment by flbulgarelli** [comment]
Allowing a complete flow of exercise submission without a user is actually too complex, and it actually doesn't worth the effort since in the end want to make users to log in. 

However, it is a good idea to let public users to list guides and look at exercises in order to reduce friction an improve search indexing. 

I have integrated those features into master
